#!/usr/bin/env node
/**
 * Generates the public leaderboard site (docs/) for GitHub Pages:
 * runs every benchmark suite through the solver and renders docs/index.md
 * plus docs/badge.svg. Exits non-zero if ANY expectation fails, so the
 * Pages site is only ever published from a green run.
 */
const fs = require('fs');
const path = require('path');
const { runSolver } = require('../src/verify');

const ROOT = path.join(__dirname, '..');

function checkCase(bindingPath, expectedVerdict, expectedInvariant) {
  if (!fs.existsSync(bindingPath)) return { ok: false, detail: 'binding missing' };
  const binding = JSON.parse(fs.readFileSync(bindingPath, 'utf-8'));
  const r = runSolver(binding);
  if (!r.ok) return { ok: false, detail: `solver error: ${r.error}` };
  if (r.output.verdict !== expectedVerdict) {
    return { ok: false, detail: `expected ${expectedVerdict}, got ${r.output.verdict}` };
  }
  if (expectedInvariant) {
    const hit = (r.output.functions || []).some((f) =>
      (f.results || []).some((x) => x.invariant === expectedInvariant && x.status === 'violated'));
    if (!hit) return { ok: false, detail: `expected violation of ${expectedInvariant}` };
  }
  return { ok: true, detail: r.output.verdict };
}

function runSuite(name, cases) {
  return {
    name,
    cases: cases.map((c) => ({ ...c, ...checkCase(c.binding, c.expected_verdict, c.expected_invariant) })),
  };
}

// ── Collect suites ──────────────────────────────────────────────────────
const suites = [];

const benchSuite = JSON.parse(fs.readFileSync(path.join(__dirname, 'suite.json'), 'utf-8'));
suites.push(runSuite('Benchmark suite — exploit classes vs safe references', benchSuite.cases.map((c) => ({
  name: c.name, class: c.class,
  binding: path.resolve(__dirname, c.binding),
  expected_verdict: c.expected_verdict,
  expected_invariant: c.expected_invariant,
}))));

const dhPath = path.join(__dirname, 'defihack', 'suite.json');
if (fs.existsSync(dhPath)) {
  const dh = JSON.parse(fs.readFileSync(dhPath), 'utf-8');
  suites.push(runSuite('DeFiHackLabs reproductions — real exploits, $261M+', dh.cases.map((c) => ({
    name: c.name, class: c.exploit_class,
    binding: path.resolve(__dirname, 'defihack', c.binding),
    expected_verdict: c.expected_verdict,
    expected_invariant: c.expected_invariant,
    loss: c.real_loss_usd,
  }))));
}

suites.push(runSuite('Real contract models', [
  'UniswapV2Swap', 'AaveLending', 'CompoundCToken',
].map((n) => ({
  name: n, class: 'real-contract',
  binding: path.join(ROOT, 'examples', `${n}.binding.json`),
  expected_verdict: 'proved',
}))));

suites.push(runSuite('ValuePacket', [
  'PaymentChannel', 'CrossChainSettlement', 'SubscriptionManager',
].map((n) => ({
  name: n, class: 'valuepacket',
  binding: path.join(ROOT, 'valuepacket', 'bindings', `${n}.binding.json`),
  expected_verdict: 'proved',
}))));

// ── Render ──────────────────────────────────────────────────────────────
const all = suites.flatMap((s) => s.cases);
const passed = all.filter((c) => c.ok).length;
const total = all.length;
const allOk = passed === total;
const ts = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

const color = allOk ? 'brightgreen' : 'yellow';
const badgeLabel = `${passed}/${total} verified`;
fs.mkdirSync(path.join(ROOT, 'docs'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'docs', 'badge.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" width="150" height="20"><rect width="70" height="20" fill="#555"/><rect x="70" width="80" height="20" fill="${allOk ? '#4c1' : '#dfb317'}"/><text x="35" y="14" fill="#fff" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11" text-anchor="middle">counterflow</text><text x="110" y="14" fill="#fff" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11" text-anchor="middle">${badgeLabel}</text></svg>\n`);

const lines = [];
lines.push('# Counterflow Leaderboard');
lines.push('');
lines.push(`![status](badge.svg)`);
lines.push('');
lines.push('Live verification results — **regenerated by CI on every push to main**.');
lines.push('Every row is a real solver run: safe references must prove, known exploits must');
lines.push('produce a counterexample. [How it works](https://github.com/KryptosAI/counterflow)');
lines.push('');
for (const s of suites) {
  const okCount = s.cases.filter((c) => c.ok).length;
  lines.push(`## ${s.name} (${okCount}/${s.cases.length})`);
  lines.push('');
  lines.push('| Case | Class | Expected | Result |');
  lines.push('|---|---|---|---|');
  for (const c of s.cases) {
    const mark = c.ok ? '✅' : '❌';
    const loss = c.loss ? ` ($${(c.loss / 1e6).toFixed(c.loss >= 1e6 ? 1 : 2)}M)` : '';
    lines.push(`| ${mark} ${c.name}${loss} | ${c.class} | ${c.expected_verdict} | ${c.detail} |`);
  }
  lines.push('');
}
lines.push('---');
lines.push(`_${passed}/${total} expectations matched · generated ${ts} by bench/leaderboard-pages.js_`);
lines.push('');

fs.writeFileSync(path.join(ROOT, 'docs', 'index.md'), lines.join('\n'));
console.log(`leaderboard: ${passed}/${total} expectations matched → docs/index.md + docs/badge.svg`);
process.exit(allOk ? 0 : 1);
